# Generated by Django 6.0.3 on 2026-03-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedslot',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Slot bloqueado', 'verbose_name_plural': 'Slots bloqueados'},
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
